### PR TITLE
Update NuGet packages

### PR DESCRIPTION
**Pull request by george-pearson**
* Update the Vs2022.csproj NuGet packages to latest.

### CODE REVIEW

**Comment by RussKie** [comment]
> * Update the Vs2015.csproj NuGet packages to be the same as Vs2022.csproj

Did you verify it worked in VS2015?

**Comment by george-pearson** [comment]
> > * Update the Vs2015.csproj NuGet packages to be the same as Vs2022.csproj
> 
> Did you verify it worked in VS2015?
I've removed the Vs2015.csproj changes (it was erroring on VS2019 🤦‍♂️). I can't seem to find a working installer for VS2015 online to test that though.
I've tested on VS2022 and VS2019 and both are working now.

**Comment by george-pearson** [comment]
Btw I'm not sure if we actually support VS2015 because the build agent is VS2019. [MinimumVisualStudioVersion ](https://github.com/gitextensions/gitextensions.vsix/blob/master/src/Vs2015/Vs2015.csproj#L35) would be set to `16.0`? I can't seem to find a working installer for VS2015 online to test that though.

**Comment by RussKie** [comment]
We shouldn't change VS2015, if we can't test it. Some of our users still use VS2015 and lower, and they use the VSIX we provide.

**Review by RussKie — APPROVED** [review]

**Pull request merged**
